--- drivers/misc/Makefile
+++ drivers/misc/Makefile
@@ -46,4 +46,3 @@
 obj-$(CONFIG_AB8500_PWM)	+= ab8500-pwm.o
 obj-y				+= lis3lv02d/
 obj-y				+= carma/
-obj-$(CONFIG_HWLAT_DETECTOR)	+= hwlat_detector.o
